Repository Azure/sap-automation, pull requests merged in 2024-03, with the labels that each got.

#553 Remove code to stop the secondary node in Oracle DB before restart
  deploy/ansible/roles-db/4.1.3-ora-dg/tasks/ora-dg-setup-secondary.yaml
Labels: bug

#559 Add a pre-flight check script
  deploy/configs/sdaf_distros.json
  deploy/configs/sdaf_skus.json
  deploy/configs/sdaf_urls.json
  deploy/scripts/Test-SDAFReadiness.ps1
Labels: enhancement

#564 Hotfix for 3.11
  deploy/ansible/roles-misc/0.3.sap-installation-media-storage-details/tasks/main.yaml
  deploy/ansible/roles-sap/5.2-pas-install/tasks/main.yaml
  deploy/pipelines/05-DB-and-SAP-installation.yaml
  deploy/pipelines/templates/run-ansible.yaml
  deploy/scripts/New-SDAFDevopsProject.ps1
Labels: hotfix

#565 Refactor Stonith SBD configuration in 1.17 Generic Pacemaker role
  deploy/ansible/roles-os/1.17-generic-pacemaker/tasks/1.17.2.0-cluster-Suse.yml
  deploy/configs/version.txt
  deploy/scripts/New-SDAFDevopsProject.ps1
Labels: hotfix

#569 Bring in Scale out improvements
  Webapp/SDAF.sln
  Webapp/SDAF/Controllers/LandscapeController.cs
  Webapp/SDAF/Controllers/SystemController.cs
  Webapp/SDAF/Models/LandscapeModel.cs
  Webapp/SDAF/Models/SystemModel.cs
  Webapp/SDAF/ParameterDetails/LandscapeDetails.json
  Webapp/SDAF/ParameterDetails/LandscapeTemplate.txt
  Webapp/SDAF/ParameterDetails/SystemDetails.json
  Webapp/SDAF/ParameterDetails/SystemTemplate.txt
  Webapp/SDAF/ParameterDetails/VM-Images.json
  Webapp/SDAF/SDAFWebApp.csproj
  Webapp/SDAF/Views/Landscape/Edit.cshtml
  Webapp/SDAF/Views/Shared/_FormPartial.cshtml
  Webapp/SDAF/Views/System/Edit.cshtml
  Webapp/SDAF/wwwroot/js/site.js
  deploy/ansible/playbook_02_os_sap_specific_config.yaml
  deploy/ansible/roles-db/4.0.3-hdb-install-scaleout/tasks/main.yaml
  deploy/ansible/roles-db/4.1.3-ora-dg/tasks/ora-dg-setup-secondary.yaml
  deploy/ansible/roles-os/1.10-networking/tasks/main.yaml
  deploy/ansible/roles-os/1.10-networking/templates/azure_interfaces.j2
  deploy/ansible/roles-sap-os/2.4-hosts-file/templates/hosts.j2
  deploy/ansible/roles-sap-os/2.6-sap-mounts/tasks/2.6.9-custom-mounts.yaml
  deploy/scripts/install_workloadzone.sh
  deploy/terraform/run/sap_landscape/output.tf
  deploy/terraform/run/sap_landscape/tfvar_variables.tf
  deploy/terraform/run/sap_landscape/transform.tf
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/run/sap_system/tfvar_variables.tf
  deploy/terraform/run/sap_system/transform.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_landscape/nsg.tf
  deploy/terraform/terraform-units/modules/sap_landscape/outputs.tf
  deploy/terraform/terraform-units/modules/sap_landscape/subnets.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/subnets.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/anf.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/avg.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/outputs.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
  deploy/terraform/terraform-units/modules/sap_system/output_files/inventory.tf
  deploy/terraform/terraform-units/modules/sap_system/output_files/sap-parameters.tmpl
  deploy/terraform/terraform-units/modules/sap_system/output_files/variables_global.tf
Labels: enhancement

#570 Add ability to deploy the Monitoring extension
  Webapp/SDAF/Models/LandscapeModel.cs
  Webapp/SDAF/Models/SystemModel.cs
  Webapp/SDAF/ParameterDetails/LandscapeDetails.json
  Webapp/SDAF/ParameterDetails/LandscapeTemplate.txt
  Webapp/SDAF/ParameterDetails/SystemDetails.json
  Webapp/SDAF/ParameterDetails/SystemTemplate.txt
  Webapp/SDAF/Views/Landscape/Edit.cshtml
  deploy/terraform/run/sap_landscape/tfvar_variables.tf
  deploy/terraform/run/sap_landscape/transform.tf
  deploy/terraform/run/sap_system/tfvar_variables.tf
  deploy/terraform/run/sap_system/transform.tf
  deploy/terraform/terraform-units/modules/sap_landscape/iscsi.tf
  deploy/terraform/terraform-units/modules/sap_landscape/nsg.tf
  deploy/terraform/terraform-units/modules/sap_landscape/subnets.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_landscape/vm.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_local.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
Labels: enhancement

#571 Control Private Endpoint DNS registration
  Webapp/SDAF/Models/LandscapeModel.cs
  Webapp/SDAF/Models/SystemModel.cs
  Webapp/SDAF/ParameterDetails/LandscapeDetails.json
  Webapp/SDAF/ParameterDetails/LandscapeTemplate.txt
  Webapp/SDAF/ParameterDetails/SystemDetails.json
  Webapp/SDAF/ParameterDetails/SystemTemplate.txt
  deploy/terraform/run/sap_landscape/module.tf
  deploy/terraform/run/sap_landscape/tfvar_variables.tf
  deploy/terraform/run/sap_system/module.tf
  deploy/terraform/run/sap_system/tfvar_variables.tf
  deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf
  deploy/terraform/terraform-units/modules/sap_landscape/storage_accounts.tf
  deploy/terraform/terraform-units/modules/sap_landscape/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/storage_accounts.tf
  deploy/terraform/terraform-units/modules/sap_system/common_infrastructure/variables_global.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/variables_global.tf
Labels: enhancement

#572 Install defender extension
  Webapp/SDAF/Models/LandscapeModel.cs
  Webapp/SDAF/Models/SystemModel.cs
  Webapp/SDAF/ParameterDetails/LandscapeDetails.json
  Webapp/SDAF/ParameterDetails/LandscapeTemplate.txt
  Webapp/SDAF/ParameterDetails/SystemDetails.json
  Webapp/SDAF/ParameterDetails/SystemTemplate.txt
  deploy/ansible/playbook_02_os_sap_specific_config.yaml
  deploy/terraform/run/sap_landscape/tfvar_variables.tf
  deploy/terraform/run/sap_landscape/transform.tf
  deploy/terraform/run/sap_system/tfvar_variables.tf
  deploy/terraform/run/sap_system/transform.tf
  deploy/terraform/terraform-units/modules/sap_landscape/iscsi.tf
  deploy/terraform/terraform-units/modules/sap_landscape/nsg.tf
  deploy/terraform/terraform-units/modules/sap_landscape/vm.tf
  deploy/terraform/terraform-units/modules/sap_system/anydb_node/vm-anydb.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-app.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-scs.tf
  deploy/terraform/terraform-units/modules/sap_system/app_tier/vm-webdisp.tf
  deploy/terraform/terraform-units/modules/sap_system/hdb_node/vm-hdb.tf
Labels: enhancement
